# The next line is used by the Flutter tool to generate the CocoaPods dependencies.
load File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')

platform :ios, '13.0'

# CocoaPods analytics sends network stats. Disable it.
install! 'cocoapods', :deterministic_uuids => false

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Resolve IPHONEOS_DEPLOYMENT_TARGET mismatch
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
